islandora_mirador.settings:
  type: config_object
  label: 'Mirador Settings'
  mapping:
    installation_type:
      type: string
      label: 'Installation type "plugin"'
    # XXX: Really, this installation_config stuff seems like a candidate for
    # config entities, especially if the installation type concept was made
    # into a plugin.
    installation_config:
      type: sequence
      label: 'Installation configuration'
      sequence:
        type: ignore
    mirador_enabled_plugins:
      type: sequence
      label: 'Enabled Plugins'
      sequence:
        type: string
        label: 'Plugin'
    iiif_manifest_url:
      type: string
      label: 'URL pattern for IIIF manifest view'
